version: '3.9'

services:
  backend:
    build: .
    container_name: medsys_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_data:/app/static
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  static_data:
