version: '3.9'

services:
  backend:
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://postgres:YF5SV7qX5Fa6OIw1@db.wolcdduoroiobtadbcup.supabase.co:5432/postgres
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./main.py:/app/main.py
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
