version: '3.9'

services:
  backend:
    build: .
    container_name: medsys_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_data:/app/static
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:YF5SV7qX5Fa6OIw1@db.wolcdduoroiobtadbcup.supabase.co:5432/postgres

volumes:
  static_data:
