-- Tabla historia_clinica_completa vinculada al bucket 'historia-completa'
CREATE TABLE IF NOT EXISTS historia_clinica_completa (
    paciente_id text,
    dni text PRIMARY KEY,
    nombre text,
    apellido text,
    fecha_nacimiento date,
    edad text,
    sexo text,
    telefono text,
    email text,
    domicilio text,
    obra_social text,
    numero_afiliado text,
    antecedentes_personales text,
    antecedentes_familiares text,
    habitos text,
    enfermedades_cronicas text,
    cirugias text,
    medicacion text,
    estudios text,
    historial_tratamientos text,
    historial_consultas text,
    institucion_id text
);
